import { MeterConfig } from "./types";

export const DEFAULT_CONFIG: MeterConfig = {
  schemaVersion: 1,
  plant: {
    name: "M/S United Payra Power Limited",
    capacity: "150 MW HFO Fired Power Plant",
    location: "Kholishakhali, Patuakhali",
    interconnection: "Energy Export to Grid at 132 KV",
  },
  intervalMinutes: 30,
  omf: 1200000,
  allowedDiscrepancyPercent: 0.2,
  meters: {
    main: "LGZ56445019",
    backup: "LGZ56445020",
  },
  registers: {
    activeExportToGrid: "1-1:1.8.0",
    activeImportFromGrid: "1-1:2.8.0",
    reactiveExportToGrid: "1-1:3.8.0",
    reactiveImportFromGrid: "1-1:4.8.0",
  },
  templateCells: {
    monthTitle: "A6",
    main: {
      endDate: "C9",
      endTime: "D9",
      startDate: "C11",
      startTime: "D11",
      activeEndExport: "F9",
      activeEndImport: "F10",
      activeStartExport: "F11",
      activeStartImport: "F12",
      reactiveEndExport: "K9",
      reactiveEndImport: "K10",
      reactiveStartExport: "K11",
      reactiveStartImport: "K12",
      activeOmg: "H9",
      reactiveOmg: "M9",
    },
    backup: {
      endDate: "C13",
      endTime: "D13",
      startDate: "C15",
      startTime: "D15",
      activeEndExport: "F13",
      activeEndImport: "F14",
      activeStartExport: "F15",
      activeStartImport: "F16",
      reactiveEndExport: "K13",
      reactiveEndImport: "K14",
      reactiveStartExport: "K15",
      reactiveStartImport: "K16",
      activeOmg: "H13",
      reactiveOmg: "M13",
    },
  },
};
